[package]
name = "c2rust-config"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "c2rust-config"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
toml_edit = "0.22"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
